# NumPy is the fundamental package for scientific computing with Python. It contains among other things:
1. a powerful N-dimensional array object.
2. sophisticated (broadcasting) functions
3. tools for integrating C/C++ and Fortran code
4. useful linear algebra, Fourier transform, and random number capabilities

In [1]:
#importing Numpy
import numpy as np
print(np.__version__)

1.16.2


In [2]:
#Creating an array of size 7 consisting zeros, ones and randint
Z=np.zeros(7)
O=np.ones(7)
R=np.random.random(7)
R=np.random.randint(10,50,(3,3))
print(Z)
print(O)
print(R)

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[[24 13 39]
 [22 26 24]
 [30 10 33]]


In [3]:
#Creating an array using arange function
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#creating an Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
#Using reshape function
arr=np.arange(1,10).reshape(3,3)

In [6]:
#Few array properties
print("The array shape is ",  arr.shape)
print("The array dimension is ", arr.ndim)
print("The array size is ", arr.size)
print("The array datatype  is ",  arr.dtype)
print("The array itemsize is ", arr.dtype.itemsize)
print("The object is ",  type(arr))

The array shape is  (3, 3)
The array dimension is  2
The array size is  9
The array datatype  is  int32
The array itemsize is  4
The object is  <class 'numpy.ndarray'>


In [7]:
#Creating a 2-D Array
arr=np.array([(1,2),(10,20)])
print(arr)

[[ 1  2]
 [10 20]]


In [8]:
#Using LinSapce and LogSpace
arr=np.linspace(10,100,10)
print(arr)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [9]:
#Using logspace
arr=np.logspace(10,100,10)
print(arr)

[1.e+010 1.e+020 1.e+030 1.e+040 1.e+050 1.e+060 1.e+070 1.e+080 1.e+090
 1.e+100]
