# Task 1

### 1. Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [1]:
try:
    a = int(input("Enter the number: "))
    b = 5/a
    print(b)
except:
    print("There is problem in the code")

Enter the number: 0
There is problem in the code


### 2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 

In [7]:
subjects = ['Americans ', 'Indians']
verbs= ['play', 'watch']
objects=['Baseball ', 'Cricket']

for i in subjects:
    for j in verbs:
        for a in objects:
            print(i,j,a)

Americans  play Baseball 
Americans  play Cricket
Americans  watch Baseball 
Americans  watch Cricket
Indians play Baseball 
Indians play Cricket
Indians watch Baseball 
Indians watch Cricket


# Task 2:

Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1. 

In [88]:
import numpy as np
op_matx = []
def gen_vander_matrix(vector, n, increasing=False):
    
    if not increasing:
        for i in range(n):
            for x in vector:
                op_matx.append(x**(n-1-i))
        x =np.array(op_matx).reshape(n, ipvector.size).T
        print(x)
                
    else:
        for i in range(n):
            for x in vector:
                op_matx.append(x**i)
        x =np.array(op_matx).reshape(n,ipvector.size).T
        print(x)
                

ipvector = np.array([1,2,3,4,5])
n =3
op_matx_dec = gen_vander_matrix(ipvector, n, False)
# op_matx_inc = gen_vander_matrix(ipvector, n, True)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
